# MoveIt uses this configuration for controller management

moveit_controller_manager: moveit_simple_controller_manager/MoveItSimpleControllerManager

moveit_simple_controller_manager:
  controller_names:
    - scara_arm_controller
    - gripper_controller

  scara_arm_controller:
    type: FollowJointTrajectory
    joints:
      - Revolute_1_Jint
      - Prismatic_1_Joint
      - Revolute_2_Joint
      - Revolute_3_Joint
  gripper_controller:
    type: FollowJointTrajectory
    joints:
      - Gripper_Left_Joint
      - Gripper_Right_Joint